interface IArmTreeScope extends ng.IScope {
    treeControl: ITreeControl;
    createModel: ICreateModel;
    queryParameters: any;
    resources: any[];
    readOnlyMode: boolean;
    editMode: boolean;
    aceConfig: any;
    $createObservableFunction: any;
    loading: boolean;
    errorResponse: any;
    readOnlyResponse: any;
    selectedResource: ISelectedResource;
    creatable: any;
    createMetaData: any;
    handleClick(data: any, action: Action, event: Event);
    invokeAction(selectedResource: ISelectedResource, action: any, event: Event);
    selectResourceHandler(branch: TreeBranch, event?: Event);
    putError: string;
    invoking: boolean;
    expandResourceHandler(branch: TreeBranch, row?: any, event?: Event, dontExpandChildren?: boolean, dontFilterEmpty?: boolean): Promise<any>;
    tenantSelect();
    enterCreateMode();
    leaveCreateMode();
    clearCreate();
    createMode: boolean;
    invokeCreate(selectedResource: ISelectedResource, event: Event, createAction: Action);
    createError: string;
    enterDataTab();
    hideDocs();
    showDocs();
    hideConfirm();
    setReadOnlyMode(readOnlyMode: boolean);
    toggleEditMode();
    showGetAction(action: Action): boolean;
    logout();
    refresh();
    user: any;
    actionResponse: string;
    tenants: ITenantDetails[];
    selectedTenant: ITenantDetails;
    resourceSearchModel: ResourceSearchDataModel;
    selectResourceSearch(item: IResourceSearchSuggestion);
    copyResUrlToClipboard(text: string): void;
    resUrlColor: string;
    resourceSearcher: ResourceSearcher;
    resourceDefinitionsCollection: ResourceDefinitionCollection;
    editorCollection: EditorCollection;
    activeTab: boolean[];
    queryParametersUpdated: boolean;
    enableDataTab(selectedResource: ISelectedResource): boolean;
}

