import * as angular from "angular";
import { ResourceDefinitionCollection } from "../AppStart/ResourceDefinitionCollection";
import {ITreeControl} from "./ITreeControl";
import {TreeBranch} from "./TreeBranch";
import {ResourceSearcher} from "../Search/ResourceSearcher";
import {EditorCollection} from "../AppStart/EditorCollection";
import {ResourceSearchDataModel} from "../Search/ResourceSearchDataModel";
import {ISelectedResource} from "./SelectedResource";

export interface IArmTreeScope extends angular.IScope {
    treeControl: ITreeControl;
    createModel: ICreateModel;
    actionsModel: any;
    resources: any[];
    readOnlyMode: boolean;
    editMode: boolean;
    aceConfig: any;
    $createObservableFunction: any;
    loading: boolean;
    errorResponse: any;
    readOnlyResponse: any;
    selectedResource: ISelectedResource;
    creatable: any;
    createMetaData: any;
    handleClick(data: any, method: string, event: Event);
    invokeAction(selectedResource: ISelectedResource, action: any, event: Event);
    selectResourceHandler(branch: TreeBranch, event?: Event);
    putError: string;
    invoking: boolean;
    expandResourceHandler(branch: TreeBranch, row?: any, event?: Event, dontExpandChildren?: boolean, dontFilterEmpty?: boolean): Promise<any>;
    tenantSelect();
    enterCreateMode();
    leaveCreateMode();
    clearCreate();
    createMode: boolean;
    invokeCreate(selectedResource: ISelectedResource, event: Event);
    createError: string;
    enterDataTab();
    hideDocs();
    showDocs();
    hideConfirm();
    setReadOnlyMode(readOnlyMode: boolean);
    toggleEditMode();
    showHttpVerb(verb: string): boolean;
    logout();
    refresh();
    user: any;
    actionResponse: string;
    tenants: ITenantDetails[];
    selectedTenant: ITenantDetails;
    resourceSearchModel: ResourceSearchDataModel;
    selectResourceSearch(item: IResourceSearchSuggestion);
    treeBranchDataOverrides: ITreeBranchDataOverrides[];
    copyResUrlToClipboard(text: string): void;
    resUrlColor: string;
    resourceSearcher: ResourceSearcher;
    resourceDefinitionsCollection: ResourceDefinitionCollection;
    editorCollection: EditorCollection;
}

